name = "DimensionalPlotRecipes"
uuid = "c619ae07-58cd-5f6d-b883-8f17bd6a98f9"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
RecipesBase = "0.7"
julia = "1"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
